id: IF13E8148
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T00:05:36+00:00'
last_modified: '2022-06-08T00:57:31.267655+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18913
  title: གྲོང་གསེབ་ཀྱི་རྒྱུན་འབྱུང་བྱས་ཉེས་དང་དེ་དག་གི་སྔོན་འགོག་ཐབས་ལམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    8CF0:
      image_group_id: I8LS18915
      title: ''
      total_pages: 312
      order: 1
      base_file: 8CF0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
